#!/usr/bin/python
import os, sys

cmm="xbacklight -set %s"
altcmm = "xrandr --output eDP1 --brightness %s"
n = 3
args = sys.argv

if len (args) < 2:
    os.system ("xbacklight -get")
    sys.exit (0)

elif args [1].isdigit ():
    os.system (cmm % args [1])
    sys.exit (0)
elif len (args) < 2:
	os.system ("xbacklight")
	sys.exit (0)

strValue = open ("/home/lg/tmp/config/xbright.txt").readlines()[0]
value = float (strValue)

if args [1] == "up":
        value = float (strValue) + n
elif args [1] == "down":
        value = float (strValue) - n

cmm = cmm % value
print (cmm)
os.system (cmm)


os.system ("echo %s > /home/lg/tmp/config/xbright.txt" % value)

