#!/usr/bin/python

"Change the names of the current directory, filling it with zeros to the right"

import os

listOfFiles = os.listdir (".")
listOfPdbs = filter (lambda x: ".mp3" in x, listOfFiles)

for pdb in listOfPdbs:
	print ">>", pdb 
	newName = pdb.replace (" ", "")
	print newName

	command = "mv " + '"' + pdb + '"' + " "  + newName
	print command
	os.system (command)
